In [1]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [2]:
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 2)
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519],
        [-0.1661, -1.5228,  0.3817, -1.0276, -0.5631],
        [-0.8923, -0.0583, -0.1955, -0.9656,  0.4224],
        [ 0.2673, -0.4212, -0.5107, -1.5727, -0.1232],
        [ 3.5870, -1.8313,  1.5987, -1.2770,  0.3255]])
tensor([[-0.4791,  1.3790,  2.5286,  0.5423,  0.1103],
        [ 0.4107, -0.9880, -0.9081, -2.2590,  0.6067]])


In [3]:
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12)) # reshape to 2 rows, 12 columns
print(x.view(2, -1)) # -1 in size auto inferred

tensor([[[ 0.9837,  0.8793, -1.4504, -1.1802],
         [ 0.4100,  0.4085,  0.2579,  1.0950],
         [ 0.6614,  1.1899,  0.8165, -0.9135]],

        [[ 1.3851, -0.8138, -0.9276,  1.1120],
         [ 1.3352,  0.6043, -0.1034, -0.1512],
         [-2.1021, -0.6200, -1.4782, -1.1334]]])
tensor([[ 0.9837,  0.8793, -1.4504, -1.1802,  0.4100,  0.4085,  0.2579,  1.0950,
          0.6614,  1.1899,  0.8165, -0.9135],
        [ 1.3851, -0.8138, -0.9276,  1.1120,  1.3352,  0.6043, -0.1034, -0.1512,
         -2.1021, -0.6200, -1.4782, -1.1334]])
tensor([[ 0.9837,  0.8793, -1.4504, -1.1802,  0.4100,  0.4085,  0.2579,  1.0950,
          0.6614,  1.1899,  0.8165, -0.9135],
        [ 1.3851, -0.8138, -0.9276,  1.1120,  1.3352,  0.6043, -0.1034, -0.1512,
         -2.1021, -0.6200, -1.4782, -1.1334]])
